// Define the decks
export const decks = {
    love: [
        { id: 'love-1', heading: 'Love', text: 'Sweet Kisses\n\n Kiss your partner gently and slowly, expressing your love with each kiss for a minute.', rating: 1 },
        { id: 'love-2', heading: 'Love', text: 'Mindful Touch\n\n Spend a few minutes touching each other slowly and deliberately, focusing on being fully present with each sensation.', rating: 1 },
        { id: 'love-3', heading: 'Love', text: 'Guided Hands\n\n Guide your partner’s hands to show exactly how and where they like to be touched.', rating: 2 },
        { id: 'love-4', heading: 'Love', text: 'Loving Gaze\n\n Hold your partner’s face and watch into their eyes for a minute.', rating: 1 },
        { id: 'love-5', heading: 'Love', text: 'Dance of Desire\n\n Pull your partner closer to you and start dancing.', rating: 1 },
        { id: 'love-6', heading: 'Love', text: 'Nose Nuzzle\n\n Share an eskimo kiss for a sweet moment.', rating: 1 },
        { id: 'love-7', heading: 'Love', text: 'Lip Lock\n\n Lock lips with your partner for two minutes straight without breaking the kiss.', rating: 2 },
        { id: 'love-8', heading: 'Love', text: 'Leg Tangle\n\n Wrap your legs around your partner while kissing them, letting your bodies tangle together for 2 minutes.', rating: 2 },
        { id: 'love-9', heading: 'Love', text: 'Heartfelt Whisper\n\n Give your partner a sweet compliment that is individual to them.', rating: 1 },
        { id: 'love-10', heading: 'Love', text: 'Lotus Embrace\n\nYou both drink and sit within the lotus position and just love each other for three minutes. <3', rating: 2 },
        { id: 'love-11', heading: 'Love', text: 'Kiss of Love\n\n Stroke your partner’s lips, tell them how much you love them and give them a deep kiss.', rating: 2 },
    ],
    foreplay: [
        { id: 'foreplay-1', heading: 'Foreplay', text: 'Whispering Desire\n\n Talk dirty in your native language for a minute.', rating: 1 },
        { id: 'foreplay-2', heading: 'Foreplay', text: 'Pinned Passion\n\n Pin your partner into the bed and start making out for a minute.', rating: 2 },
        { id: 'foreplay-3', heading: 'Foreplay', text: 'Toy Tease\n\n Stimulate your partner with a toy or yourself for a minute.', rating: 2 },
        { id: 'foreplay-4', heading: 'Foreplay', text: 'Bondage Bliss\n\n Tie your partner to lightly restrain them, giving you control over their pleasure for three minutes. (No fucking, teasing allowed)', rating: 3 },
        { id: 'foreplay-5', heading: 'Foreplay', text: 'Nipple Play\n\n Stimulate your partner’s nipple with anything you want for two minutes.', rating: 2 },
        { id: 'foreplay-6', heading: 'Foreplay', text: 'Blindfold Sensory\n\n Blindfold your partner and start teasing them in any way for one and a half minutes.', rating: 2 },
        { id: 'foreplay-7', heading: 'Foreplay', text: 'Loving Restraint\n\n Tie your partner’s hands gently and shower them with affection while they are restrained for three minutes.', rating: 2 },
        { id: 'foreplay-8', heading: 'Foreplay', text: 'Hidden Heat\n\n Put your hand down your partner’s underwear and do whatever you want for three minutes.', rating: 3 },
        { id: 'foreplay-9', heading: 'Foreplay', text: 'Moan Tease\n\n Blindfold your partner and tease them for so long until their first moan.', rating: 2 },
        { id: 'foreplay-10', heading: 'Foreplay', text: 'Strawberry Seduction\n\n Lick your partner’s nipple or eat them with strawberry for a minute.', rating: 1 },
        { id: 'foreplay-11', heading: 'Foreplay', text: 'Choke & Kiss\n\n Pin your partner down and choke them while teasing them with kisses for two minutes.', rating: 3 },
        { id: 'foreplay-12', heading: 'Foreplay', text: 'Lap Lock\n\n Sit on your partner’s lap and kiss each other for a minute.', rating: 1 },
        { id: 'foreplay-13', heading: 'Foreplay', text: 'Erotic Straddle\n\n Lay your partner down, sit on them, and erotically straddle them with your intimate area (both areas are naked) for two minutes. Do not let it slip inside!', rating: 3 },
        { id: 'foreplay-14', heading: 'Foreplay', text: 'Hair Tangle Kiss\n\n Kiss your partner and pull their hair for a minute and a half.', rating: 2 },
        { id: 'foreplay-15', heading: 'Foreplay', text: 'Drink & Devour\n\n Let your partner finish their drink while eating them. If their drink is below half, refill.', rating: 2 },
        { id: 'foreplay-16', heading: 'Foreplay', text: 'Intimate Kiss\n\n Kiss your partner’s intimate area or start eating them for a minute.', rating: 3 },
        { id: 'foreplay-17', heading: 'Foreplay', text: 'Neck & Thrill\n\n Touch your partner’s intimate area while kissing their neck for two minutes.', rating: 3 },
        { id: 'foreplay-18', heading: 'Foreplay', text: 'Guided Fantasy\n\n Take your partner’s hand and use it to pleasure yourself for a minute.', rating: 2 },
        { id: 'foreplay-19', heading: 'Foreplay', text: 'Rough Passion\n\n Push your partner roughly into the bed, pull their hair roughly, and kiss their neck roughly for two minutes.', rating: 3 },
        { id: 'foreplay-20', heading: 'Foreplay', text: 'Cuddle Control\n\n Hug your partner, whispering dirty talk in your native language while stroking their hair, while also rubbing against them sometimes for a minute and a half.', rating: 2 },
        { id: 'foreplay-21', heading: 'Foreplay', text: 'Dark Domination\n\n Turn the lights off and dominate your partner, telling them who is in control for two minutes.', rating: 3 },
        { id: 'foreplay-22', heading: 'Foreplay', text: 'Dark Exploration\n\n Turn the lights off and explore your partner’s body for three minutes.', rating: 3 },
        { id: 'foreplay-23', heading: 'Foreplay', text: 'Spooning Seduction\n\n Spoon your partner and tease them with your hands and lips from behind or front for two minutes.', rating: 2 },
        { id: 'foreplay-24', heading: 'Foreplay', text: 'Ass Worship\n\n Turn your partner onto their stomach and stroke their ass before hitting them three times.', rating: 2 },
        { id: 'foreplay-25', heading: 'Foreplay', text: 'Surprise Pleasure\n\n Blindfold your partner and lay them down into their position;\nBF: Put a toy into her without warning and fuck her hard with it for 30 seconds.\nGF: Give him a very fast, firm, and intense hand job for 30 seconds. If you make him come, he drinks your next card.', rating: 3 },
        { id: 'foreplay-26', heading: 'Foreplay', text: 'Lip Bite\n\n Bite and kiss your partner’s lips for a time.', rating: 1 },
        { id: 'foreplay-27', heading: 'Foreplay', text: 'Hickey Time\n\n Draw your partner closely and kiss their neck intensely for two minutes.', rating: 2 },
        { id: 'foreplay-28', heading: 'Foreplay', text: 'Under Pleasure Control\n\n You choose every action your partner must perform on you, but you cannot touch them for two minutes.', rating: 2 },
        { id: 'foreplay-29', heading: 'Foreplay', text: 'Undercover Kisses\n\n Kiss your partner’s body under the covers for two minutes.', rating: 2 },
        { id: 'foreplay-30', heading: 'Foreplay', text: 'Whispering Desire\n\n Talk dirty in your native language for a minute.', rating: 1 },
    ],
    sex: [
        { id: 'sex-1', heading: 'Sex', text: 'Tied Heaven\n\nBlindfold your partner, tie their hands and / or legs and fuck them as you please for four minutes.', rating: 3 },
        { id: 'sex-2', heading: 'Sex', text: 'Position Of The Night\n\nTry a new sex position for two minutes.', rating: 1 },
        { id: 'sex-3', heading: 'Sex', text: 'Sex Tape\n\nCreate a Sex Tape together.', rating: 3 },
        { id: 'sex-4', heading: 'Sex', text: '69 Heaven\n\nHave a 69 for three minutes.', rating: 2 },
        { id: 'sex-5', heading: 'Sex', text: 'Deep Stay\n\nLet it inside deeply within a position that fits, love each other but do not move it for two minutes.', rating: 3 },
        { id: 'sex-6', heading: 'Sex', text: 'Mouth Worship\n\nBF: Fuck her mouth for a minute.\nGF: Sit on his face and let him pleasure you for a minute.', rating: 2 },
        { id: 'sex-7', heading: 'Sex', text: 'Quickie Time!?\n\nIf the last digit of the clock is even, you both drink, else have sex for three minutes.', rating: 3 },
    ],

    roleplay: [
        { id: 'roleplay-1', heading: 'Roleplay', text: 'Pet Fantasy\n\nAct as a pet and annoy your partner in a sweet way for two minutes.', rating: 1 },
        { id: 'roleplay-2', heading: 'Roleplay', text: 'Kidnapp Fantasy\n\nAct as a kidnapper. Let your partner walk through the door while you turn off the lights, grab their neck from behind and keep their mouth shut. Act in this role for two minutes.', rating: 2 },
        { id: 'roleplay-3', heading: 'Roleplay', text: 'Rape Fantasy\n\nGrab and start raping your partner by taking off their cloths roughly and beating them when they act too slow or not the way you want. Act in this role for two minutes.', rating: 3 },
        { id: 'roleplay-4', heading: 'Roleplay', text: 'Masochist Fantasy\n\nAsk your partner kindly if they could choke and abuse you because you wanteded to be a benefit for so long.', rating: 1 }
    ],

    drink: [
        { id: 'drink-1', heading: 'Drink', text: 'Anniversary Sip\n\nTake a drink for each year you have been together.' },
        { id: 'drink-2', heading: 'Drink', text: 'Body Shots\n\nTake a shot off your partner’s body.', rating: 1 },
        { id: 'drink-2', heading: 'Drink', text: 'Body Shots\n\nTake a shot off your partner’s body.', rating: 1 },
        { id: 'drink-2', heading: 'Drink', text: 'Body Shots\n\nTake a shot off your partner’s body.', rating: 1 },
        { id: 'drink-3', heading: 'Drink', text: 'Blink Challenge\n\nStare your partner into the eyes, whoever blinks, drinks.', rating: 2 },
        { id: 'drink-4', heading: 'Drink', text: 'Finish Line\n\nThe person who is closer to finish finishes their drink.' },
        { id: 'drink-5', heading: 'Drink', text: 'Partner\'s Sip\n\nDrink your partner\'s drink.' }
    ],

    fun: [
        { id: 'fun-1', heading: 'Fun', text: 'Underwear Fashion\n\nModel in your favorite underwear.', rating: 2 },
        { id: 'fun-2', heading: 'Fun', text: 'Lick & Kiss\n\nLick your partner from feet to head, finishing with a kiss.', rating: 1 },
        { id: 'fun-3', heading: 'Fun', text: 'Position Guess\n\nName the last sex position, guess wrong and drink double this card.', rating: 2 },
        { id: 'fun-4', heading: 'Fun', text: 'Color Guess\n\nGuess your partner\'s underwear color, guess wrong and drink double this card.', rating: 2 },
        { id: 'fun-5', heading: 'Fun', text: 'Hickey Roulette\n\nLet your partner choose from 1-5, and give them that many hickeys.', rating: 1 },
        { id: 'fun-6', heading: 'Fun', text: 'Naughty Snapshot\n\nAsk your partner to go outside the room and send them a naughty picture or video.', rating: 1 },
        { id: 'fun-7', heading: 'Fun', text: 'Commanded Desire\n\nDo whatever your partner asks for.', rating: 2 },
        { id: 'fun-8', heading: 'Fun', text: 'Moan Mimic\n\nImitate your partner\'s moaning.', rating: 1 },
        { id: 'fun-9', heading: 'Fun', text: 'Finger Seduction\n\nSuck your partner\'s fingers.', rating: 1 },
        { id: 'fun-10', heading: 'Fun', text: 'Licking Time\n\nLick your partner anywhere you want for a minute.', rating: 1 },
        { id: 'fun-11', heading: 'Fun', text: 'Shoulder Bliss\n\nGive your partner a relaxing massage for a minute.', rating: 1 },
        { id: 'fun-12', heading: 'Fun', text: 'Make-Up Makeover\n\nApply make-up on your partner.', rating: 2 },
        { id: 'fun-13', heading: 'Fun', text: 'Playful Bite\n\nTake your partner\'s arm and bite a spot.', rating: 2 },
        { id: 'fun-14', heading: 'Fun', text: 'Confession\n\nShare something you like or dislike about a friend of your partner.', rating: 1 },
        { id: 'fun-15', heading: 'Fun', text: 'Lust Language\n\nOrder your partner to repeat your words in your native language after you gave them a long kiss.', rating: 2 },
        { id: 'fun-16', heading: 'Fun', text: 'Thigh Worship\n\nStroke and kiss your partner’s thighs while maintaining intense eye contact for a minute.', rating: 3 },
        { id: 'fun-17', heading: 'Fun', text: 'Picture Perfect\n\nMake a picture together.', rating: 1 },
        { id: 'fun-18', heading: 'Fun', text: 'Love Mark\n\nMark your partner’s belly with your lips with waterproof lipstick.', rating: 1 },
        { id: 'fun-19', heading: 'Fun', text: 'Sexy Overhaul\n\nAsk your partner to go outside the room and dress yourself in something sexy to surprise them.', rating: 2 },
        { id: 'fun-20', heading: 'Fun', text: 'Tickle & Tease\n\nAlternate between gentle tickles and sensual touches for two minutes.', rating: 1 }
    ]
};
export const randomCards = [
    { id: 'random-1', heading: "Spicy Snapshot", text: "Take secretly a picture during sex of you and show it them later." },
    { id: 'random-2', heading: "Moan Trigger", text: "Everytime your partner moans during sex, keep their mouth shout with your lips and make them moan even harder." },
    { id: 'random-3', heading: "Strip Drinking", text: "For every double card, take off a clothing part. If you are naked and get another double card, your partner can decide on what you wear." },
    { id: 'random-3', heading: "Stroke & Caress", text: "Stroke your partner anywhere while they perform their next tasks." },
    { id: 'random-3', heading: "Take a Moan", text: "For the rest of the game, each time one of you moans, you drink." },
    { id: 'random-3', heading: "Kiss Before Play ", text: "Every time it is your turn you must kiss your partner before continuing." },
    { id: 'random-3', heading: "Intimate Glance", text: "Every time you look at your partner during the game, you must give them a soft kiss." },
    { id: 'random-3', heading: "Kiss On Command", text: "Every time your partner says kiss me, you must immediately kiss them." },
    { id: 'random-3', heading: "Double Trouble", text: "Your next card must be done twice." },
    { id: 'random-3', heading: "Magnetic Touch", text: "You have to stay in contact with your partner's genital at all times." },
];
